import images from '~/assets/images';
import type { Course } from '~/models';

export const courseData: Course[] = [
    {
        courseId: 1,
        imageUrl: images.courseImg1,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.2,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 2,
        imageUrl: images.courseImg2,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.0,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 3,
        imageUrl: images.courseImg3,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 3.8,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 4,
        imageUrl: images.courseImg4,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.9,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 5,
        imageUrl: images.courseImg5,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.5,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 6,
        imageUrl: images.courseImg6,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.2,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 7,
        imageUrl: images.courseImg7,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.1,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 8,
        imageUrl: images.courseImg8,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 3.7,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 9,
        imageUrl: images.courseImg9,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.7,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 10,
        imageUrl: images.courseImg10,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.6,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 11,
        imageUrl: images.courseImg11,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.9,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 12,
        imageUrl: images.courseImg12,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.0,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 13,
        imageUrl: images.courseImg13,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.1,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 14,
        imageUrl: images.courseImg14,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.5,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 15,
        imageUrl: images.courseImg15,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.2,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 16,
        imageUrl: images.courseImg16,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 3.5,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 17,
        imageUrl: images.courseImg17,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4.7,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
    {
        courseId: 18,
        imageUrl: images.courseImg18,
        title: 'English Pronunciation - Complete Guide to English Speaking',
        instructor: 'Francis Carlisle: Last Minute English',
        rating: 4,
        ratingCount: '6,976',
        price: '₫1,629,000',
    },
];
